services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: formbuilder
      POSTGRES_USER: formbuilder
      POSTGRES_PASSWORD: formbuilder123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U formbuilder"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://formbuilder:formbuilder123@db:5432/formbuilder
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: